# Generated by Django 5.0 on 2023-12-30 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('discount_rate', models.FloatField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_rate', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.IntegerField(default=1)),
                ('discount_rate', models.FloatField()),
                ('discount_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_product', to='Product.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotionsAndvouchers.promotion')),
                ('required_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_product', to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotionsAndvouchers.promotion')),
            ],
        ),
    ]
